name: Validar back-end

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore BibliotecaEscolar.slnx
      - run: dotnet build BibliotecaEscolar.slnx --no-restore --configuration Release
      - run: dotnet test BibliotecaEscolar.slnx --no-build --configuration Release
